defaults:
  - _self_

### Experiment Details ###
exp_name: .../SCM/scheduler_${scheduler.timesteps}_n_samples_${n_samples}_guidance_scale_${guidance_scale}
out_h5_name: diffusion_data.h5

n_samples: 5
# guidance_scale: 0.1

age_scale: 1.0
sex_scale: 1.0
site_scale: 1.0

# this can be either original or SCM
sample_type: original

# can be a dict with keys or none
SCM: null


### Data Details - adjust on HPC-Cluster or Own Servers###
original_csv_path: .../scm_of_choice.csv
diffusion:
  cfg_path: "/.../.hydra/config.yaml"
  checkpoint_path: ".../chkpts/last.ckpt"

encoder:
  cfg_path: ".../.hydra/config.yaml"
  checkpoint_path: ".../chkpts/epoch-18-val_loss-0.0155.ckpt"

classifier:
  cfg_path: ".../.hydra/config.yaml"
  checkpoint_path: ".../chkpts/last.ckpt"

### Data Generation Details ###
scheduler:
  timesteps: 50


### Hydra Job Details ###
hydra:
  run:
    dir: diffusion_data/${exp_name}/
  job:
    chdir: True
  sweep:
    dir: diffusion_data
    subdir: ${exp_name}
  sweeper:
    params:
      +guidance_scale: 0.5

test_ratio: 0.15
val_ratio: 0.15